/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_openrds_OpenRdsJni */

#ifndef _Included_net_sf_openrds_OpenRdsJni
#define _Included_net_sf_openrds_OpenRdsJni
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: INSTANCE */
/*
 * Class:     net_sf_openrds_OpenRdsJni
 * Method:    getMemoryAmount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_openrds_OpenRdsJni_getMemoryAmount
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_openrds_OpenRdsJni
 * Method:    getClockFrequency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_openrds_OpenRdsJni_getClockFrequency
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
